---

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-aux.git
  version: v1.0.0-3
  name: auxiliary
- src: git+https://gitlab.com/etke.cc/roles/backup_borg.git
  version: v1.2.6-1.8.5-0
  name: backup_borg
- src: git+https://github.com/devture/com.devture.ansible.role.container_socket_proxy.git
  version: v0.1.1-2
  name: container_socket_proxy
- src: git+https://github.com/geerlingguy/ansible-role-docker
  version: 7.0.2
  name: docker
- src: git+https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python.git
  version: 129c8590e106b83e6f4c259649a613c6279e937a
  name: docker_sdk_for_python
- src: git+https://gitlab.com/etke.cc/roles/etherpad.git
  version: v1.9.3-0
  name: etherpad
- src: git+https://gitlab.com/etke.cc/roles/grafana.git
  version: v10.2.2-0
  name: grafana
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-jitsi.git
  version: v9111-0
  name: jitsi
- src: git+https://gitlab.com/etke.cc/roles/ntfy.git
  version: v2.8.0-0
  name: ntfy
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: c1f40e82b4d6b072b6f0e885239322bdaaaf554f
  name: playbook_help
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: 9b4b088c62b528b73a9a7c93d3109b091dd42ec6
  name: playbook_runtime_messages
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_state_preserver.git
  version: ff2fd42e1c1a9e28e3312bbd725395f9c2fc7f16
  name: playbook_state_preserver
- src: git+https://github.com/devture/com.devture.ansible.role.postgres.git
  version: v16.1-0
  name: postgres
- src: git+https://github.com/devture/com.devture.ansible.role.postgres_backup.git
  version: 5dd334c0b7f0a2795023ec9ece747c3ea3da06f2
  name: postgres_backup
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus.git
  version: v2.48.0-0
  name: prometheus
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-node-exporter.git
  version: v1.7.0-0
  name: prometheus_node_exporter
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-postgres-exporter.git
  version: v0.14.0-0
  name: prometheus_postgres_exporter
- src: git+https://gitlab.com/etke.cc/roles/redis.git
  version: v7.2.0-0
  name: redis
- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: v1.0.0-0
  name: systemd_docker_base
- src: git+https://github.com/devture/com.devture.ansible.role.systemd_service_manager.git
  version: v1.0.0-2
  name: systemd_service_manager
- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: v1.0.0-0
  name: timesync
- src: git+https://github.com/devture/com.devture.ansible.role.traefik.git
  version: v2.10.5-2
  name: traefik
- src: git+https://github.com/devture/com.devture.ansible.role.traefik_certs_dumper.git
  version: v2.8.1-0
  name: traefik_certs_dumper
